[package]
name = "wgpu-raytracer"
version = "0.1.0"
authors = ["Joe Graziano <joeyg11@vt.edu>"]
edition = "2018"

[dependencies]
image = "0.23"
winit = "0.22"
wgpu = "0.5.0"
futures = "0.3.5"
bytemuck = "1.2"

[build-dependencies]
glsl-to-spirv = "0.1.7"