[package]
name = "wgpu-raytracer"
version = "0.1.0"
authors = ["Joe Graziano <joeyg11@vt.edu>"]
edition = "2018"

[dependencies]
image = "0.23"
winit = "0.22"
wgpu = "0.6.0"
futures = "0.3.5"
bytemuck = "1.2"
glam = "0.9.4"
rand = "0.7"
shaderc = "0.6"
